export const questionsData = [
  { question: "What is a private equity fund?", category: "Private Markets" },
  {
    question: "How do venture capital funds operate?",
    category: "Private Markets",
  },
  { question: "What is a hedge fund?", category: "Fund Types" },
  { question: "How is a mutual fund structured?", category: "Fund Types" },
  {
    question:
      "What are the key differences between private equity and venture capital?",
    category: "Private Markets",
  },
  {
    question: "How do private equity firms create value?",
    category: "Private Markets",
  },
  {
    question: "What is due diligence in private markets?",
    category: "Investment Process",
  },
  {
    question: "How are investment rounds structured in venture capital?",
    category: "Venture Capital",
  },
  {
    question: "What are the different types of funds in private markets?",
    category: "Fund Types",
  },
  {
    question: "What is an angel investor?",
    category: "Early Stage Investment",
  },
  { question: "How is a fund-of-funds structured?", category: "Fund Types" },
  { question: "What is a leveraged buyout (LBO)?", category: "Private Equity" },
  {
    question: "What are common private market investment strategies?",
    category: "Investment Strategies",
  },
  {
    question: "What is a Special Purpose Acquisition Company (SPAC)?",
    category: "Investment Vehicles",
  },
  { question: "What is carried interest?", category: "Private Equity" },
  { question: "How does a fund manager operate?", category: "Fund Management" },
  {
    question: "What are exit strategies in private equity?",
    category: "Private Equity",
  },
  {
    question: "What is a growth equity investment?",
    category: "Private Markets",
  },
  { question: "How is fund performance measured?", category: "Fund Metrics" },
  { question: "What is an IPO?", category: "Exit Strategies" },
  {
    question: "What are the key metrics in private equity?",
    category: "Private Equity",
  },
  { question: "What is a limited partner (LP)?", category: "Investment Roles" },
  {
    question: "What is an accredited investor?",
    category: "Investor Requirements",
  },
  {
    question: "What is the role of a general partner (GP)?",
    category: "Investment Roles",
  },
  { question: "What is venture debt?", category: "Venture Capital" },
  { question: "How does a capital call work?", category: "Fund Operations" },
  {
    question: "What is an investment thesis?",
    category: "Investment Strategy",
  },
  {
    question: "How does valuation work in private equity?",
    category: "Private Equity",
  },
  { question: "What is EBITDA?", category: "Financial Metrics" },
  { question: "What is a term sheet?", category: "Venture Capital" },
  {
    question: "How does mezzanine financing work?",
    category: "Private Markets",
  },
  { question: "What is a secondary market?", category: "Markets" },
  { question: "What is a management fee?", category: "Fund Fees" },
  { question: "What is a capital commitment?", category: "Fund Operations" },
  {
    question: "How do venture capitalists evaluate startups?",
    category: "Venture Capital",
  },
  { question: "What are portfolio companies?", category: "Private Equity" },
  { question: "What is private debt?", category: "Debt Markets" },
  {
    question: "How do growth funds differ from buyout funds?",
    category: "Private Equity",
  },
  { question: "What is Series A funding?", category: "Venture Capital" },
  {
    question: "What is equity crowdfunding?",
    category: "Alternative Investments",
  },
  { question: "How do dividends work?", category: "Financial Returns" },
  {
    question: "What are the risks in private equity?",
    category: "Risk Management",
  },
  { question: "What is a unicorn company?", category: "Venture Capital" },
  {
    question: "How does fundraising work for private equity?",
    category: "Fund Operations",
  },
  { question: "What is dry powder?", category: "Private Equity" },
  { question: "What are distressed assets?", category: "Investment Types" },
  { question: "What is asset allocation?", category: "Investment Strategy" },
  {
    question: "How do private equity firms exit investments?",
    category: "Exit Strategies",
  },
  { question: "What is an evergreen fund?", category: "Fund Types" },
  { question: "What are co-investments?", category: "Investment Types" },
  { question: "What is preferred equity?", category: "Equity Types" },
  {
    question: "How does a convertible note work?",
    category: "Investment Vehicles",
  },
  { question: "What is impact investing?", category: "Investment Strategy" },
  { question: "What is fund liquidity?", category: "Fund Metrics" },
  {
    question: "What are the stages of venture funding?",
    category: "Venture Capital",
  },
  { question: "What is a minority stake?", category: "Ownership" },
  {
    question: "How are returns generated in private equity?",
    category: "Financial Returns",
  },
  {
    question: "What is syndication in private markets?",
    category: "Investment Process",
  },
  { question: "How do secondary buyouts work?", category: "Private Equity" },
  { question: "What is an anchor investor?", category: "Investment Roles" },
  {
    question: "What is the difference between public and private markets?",
    category: "Markets",
  },
  { question: "What is shareholder value?", category: "Equity" },
  {
    question: "How is risk managed in private equity?",
    category: "Risk Management",
  },
  {
    question: "What is fund diversification?",
    category: "Investment Strategy",
  },
  { question: "What is a PIPE investment?", category: "Investment Vehicles" },
  { question: "What is carried interest?", category: "Fund Fees" },
  { question: "What is fund vintage?", category: "Fund Metrics" },
  { question: "How do GPs and LPs collaborate?", category: "Fund Management" },
  { question: "What is an acquisition?", category: "Investment Strategies" },
  {
    question: "How do investors profit from IPOs?",
    category: "Exit Strategies",
  },
  { question: "What is a recapitalization?", category: "Corporate Finance" },
  { question: "What is seed funding?", category: "Venture Capital" },
  { question: "What are common exit strategies?", category: "Exit Strategies" },
  { question: "What is a lock-up period?", category: "Fund Terms" },
  { question: "What is growth capital?", category: "Private Markets" },
  { question: "What are fund returns?", category: "Fund Metrics" },
  {
    question: "What is an investment memorandum?",
    category: "Investment Process",
  },
  { question: "How do fund closures work?", category: "Fund Operations" },
  {
    question: "What is the role of a family office?",
    category: "Investment Roles",
  },
  {
    question: "How do equity distributions work?",
    category: "Financial Returns",
  },
  { question: "What is NAV?", category: "Fund Metrics" },
  { question: "What is shareholder equity?", category: "Equity" },
  { question: "What is a follow-on investment?", category: "Investment Types" },
  {
    question: "How does revenue generation work in private equity?",
    category: "Private Equity",
  },
  { question: "What is a financial sponsor?", category: "Private Markets" },
  { question: "What is a mezzanine loan?", category: "Debt Markets" },
  { question: "What are common fund structures?", category: "Fund Types" },
  { question: "How are dividends calculated?", category: "Financial Returns" },
  { question: "What are leveraged buyouts?", category: "Private Equity" },
  { question: "What is strategic investing?", category: "Investment Strategy" },
  {
    question: "What is the purpose of an investment committee?",
    category: "Investment Process",
  },
  { question: "What are fund waterfall structures?", category: "Fund Terms" },
  { question: "What is a private placement?", category: "Investment Vehicles" },
  { question: "What are liquidation preferences?", category: "Fund Terms" },
  {
    question: "How does private equity impact company management?",
    category: "Private Equity",
  },
  { question: "What is ESG investing?", category: "Investment Strategy" },
];
